src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category of Merchandise</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Notebooks</fullName>
                    <default>true</default>
                    <label>Notebooks</label>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>Keyboards</fullName>
                </value>
                <value>
                    <fullName>Mouses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <description>Picture of Merchandise</description>
        <label>Picture</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchController.cls
/**
 * Created by Serhii on 24.10.2018.
 */

public with sharing class MerchController {

    @AuraEnabled
    public static List<Merchandise__c> getMerchandises() {
        String[] fieldsToCheck = new String[]{
                'Id', 'Name', 'Picture__c', 'Category__c', 'Description__c',
                'Price__c', 'Quantity__c'
        };

        Map<String, Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Merchandise__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
// OK, they're cool, let 'em through
        return [
                SELECT Id, Name, Picture__c, Category__c, Description__c,
                        Price__c, Quantity__c
                FROM Merchandise__c];

//        String categoryString = 'Quantity__c>0';
  //      return getCategory(categoryString);
    }

    @AuraEnabled
    public static List<Merchandise__c> getNotes() {
        String categoryString = 'Notebooks';
        return getCategory(categoryString);
    }

    @AuraEnabled
    public static List<Merchandise__c> getMons() {
        String categoryString = 'Monitors';
        return getCategory(categoryString);
    }
    @AuraEnabled
    public static List<Merchandise__c> getKes() {
        String categoryString = 'Keyboards';
        return getCategory(categoryString);
    }
    @AuraEnabled
    public static List<Merchandise__c> getMouses() {
        String categoryString = 'Mouses';
        return getCategory(categoryString);
    }

    public static List<Merchandise__c> getCategory(String categoryString) {

// Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[]{
                'Id', 'Name', 'Picture__c', 'Category__c', 'Description__c',
                'Price__c', 'Quantity__c'
        };

        Map<String, Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Merchandise__c.fields.getMap();

        for (String field : fieldsToCheck) {
            if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
// OK, they're cool, let 'em through
        return [
                SELECT Id, Name, Picture__c, Category__c, Description__c,
                        Price__c, Quantity__c
                FROM Merchandise__c
                WHERE Category__c = :categoryString
        ];
    }

}